Mayhem integration
mayhemheroes/parity-bridges-common pull request #1
Opened 2022-05-26 01:42 UTC by code-terror

2022-07-23 23:40 UTC, xansec requested changes
Please make the requested changes.

2022-07-23 23:40 UTC, xansec commented on Dockerfile
> -# Builds images used by the bridge.
Please do not modify upstream Dockerfiles.

2022-07-23 23:40 UTC, xansec commented on Mayhemfile
> +project: code-terror/parity-bridges-common
Please use a generic project name (omit your username).

2022-07-23 23:40 UTC, xansec commented on ci.Dockerfile
> -# This file is a "runtime" part from a builder-pattern in Dockerfile, it's used in CI.
Please do not delete upstream files without good reason.

2022-07-24 03:39 UTC, code-terror commented
Pushed the requested changes.. These were the initial submissions I worked on..So I was experimenting and playing around..So you would notice these issues..

2022-07-24 03:39 UTC, code-terror commented
@xansec

2022-07-25 18:55 UTC, xansec requested changes
Hmm, the two upstream Dockerfiles are still showing as modified, but I cna't figure out why? Maybe it's the missing newline? Please make the requested changes.

2022-07-25 19:47 UTC, code-terror commented
@xansec should be done now

2022-07-25 19:48 UTC, xansec commented
Awesome!

2022-07-25 19:48 UTC, merged